### ISSUE TITLE
Error in angular 5

### ISSUE THREAD

**Issue by ghost** [devsullo/ng2-STOMP-Over-WebSocket#10]
Hello, actually I'm working in an project with angular 5, before that I worked with angular 4. But I decided upgraded angular. However the following errors appeared. Does someone has a ide about that?.
Please I need your help.

ERROR in ./node_modules/ng2-stomp-service/dist/stomp.service.ts
Module build failed: Error: /home/jose/projects/OpenMDM-FrontEnd-master/node_modules/ng2-stomp-service/dist/stomp.service.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/home/jose/projects/OpenMDM-FrontEnd-master/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:649:23)
    at plugin.done.then (/home/jose/projects/OpenMDM-FrontEnd-master/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./node_modules/ng2-stomp-service/index.js 2:20-51
 @ ./src/app/devices/devices.module.ts
 @ ./src/app/layout/shared/layout.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

**Comment by nedpuganti** [comment]
@joseSierra94 
add this into your tsconfig.json

"include": [
    "src/**/*",
    "node_modules/ng2-stomp-service/dist/stomp.service.ts"
  ]

**Comment by trihex** [comment]
That is a hack and not a solution.  The project should be packaged in the proper Angular package format.  Are there any plans to do this?

**Comment by lmyslinski** [comment]
Any progress on this? Also, the hack works for running the app, but I didn't get it to work with karma and jasmine. Does anyone have a temporary workaround for testing?
