### ISSUE TITLE
Compile error with Angular 6

### ISSUE THREAD

**Issue by sgrillon14** [devsullo/ng2-STOMP-Over-WebSocket#12]
ERROR in ./node_modules/ng2-stomp-service/dist/stomp.service.ts
Module build failed: Error: C:\workspace\spring-boot-angular2-stomp\src\main\ng\node_modules\ng2-stomp-service\dist\stomp.service.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library
repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\workspace\spring-boot-angular2-stomp\src\main\ng\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:709:23)
    at plugin.done.then (C:\workspace\spring-boot-angular2-stomp\src\main\ng\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by sgrillon14** [comment]
I add this into your tsconfig.json

"include": [
"src/**/*",
"node_modules/ng2-stomp-service/dist/stomp.service.ts"
]

but now I have

```
ERROR in ./node_modules/stompjs/lib/stomp-node.js
Module not found: Error: Can't resolve 'net' in 'C:\workspace\spring-boot-angular2-stomp\src\main\ng\node_modules\stompjs\lib'
```

**Comment by elunaNeo** [comment]
I'm facing the very same error right now when trying to stompjs.

**Comment by dmorton2297** [comment]
If there was any resolution to this issue, please post.

**Comment by TomasTopinka** [comment]
Same problem here :(

**Comment by NSnietol** [comment]
Same problema, 
Angular CLI: 8.2.1
Node: 10.15.3
OS: win32 x64
Angular:
