### ISSUE TITLE
Problems with disconnect and reconnect

### ISSUE THREAD

**Issue by johneast** [devsullo/ng2-STOMP-Over-WebSocket#3]
Hi,

I'm having an issue with re-connecting. In the web app I'm making, only one page needs a stomp connection. When the user enters that page a stomp connection is made and then a subscription is made. When the user leaves that page, unsubscribe is called, followed by a disconnect. When the user goes back to that page, an InvalidStateError is received when trying to subscribe again.
My code is shown below.
```
export class MyComponent implement OnInit, OnDestory {

    subscription: any;

    constructor(private stompService: StompService){}

    ngOninit(): void {
        this.stompService.configure({
            host: "***mystompurl***"
        });

        this.stompService.startConnect()
            .then(() => {
                console.log('Stomp connected');
                this.subscription = this.stompService.subscribe('/topic/mytopic', (msg, headers) => {
                    // Message handler code
                }); 
            });
    }

    ngOnDestroy(): void {
        if (this.subscription) {
            console.log('Unsubscribing');
            this.stompService.unsubscribe(this.subscription);
            this.subscription = null;
        }
       this.stompService.disconnect().then(() => console.log('Stomp disconnected');
    }
}
```

The first time the component is initialised everything works fine and messages can be sent and received. When the user leaves the page and the component is destroyed I can see the 'Unsubscribing' and 'Stomp disconnected' console entries.

The second time the user goes into the page and the component is initialised again, I get the 'Stomp connected' console entry, but then I immediately receive the following stack trace.

```
Error: InvalidStateError: The connection has not been established yet
    at ZoneAwareError (http://localhost:4200/polyfills.bundle.js:6988:33)
    at SockJS.send (http://localhost:4200/vendor.bundle.js:119988:11)
    at Client._transmit (http://localhost:4200/vendor.bundle.js:70078:26)
    at Client.subscribe (http://localhost:4200/vendor.bundle.js:70298:12)
    at StompService.subscribe (http://localhost:4200/vendor.bundle.js:100552:27)
    at http://localhost:4200/main.bundle.js:877:53
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6330:26)
    at Object.onInvoke (http://localhost:4200/vendor.bundle.js:4753:37)
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.bundle.js:6329:32)
    at Zone.run (http://localhost:4200/polyfills.bundle.js:6122:43)
    at http://localhost:4200/polyfills.bundle.js:6709:57
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6363:31)
    at Object.onInvokeTask (http://localhost:4200/vendor.bundle.js:4744:37)
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.bundle.js:6362:36)
    at Zone.runTask (http://localhost:4200/polyfills.bundle.js:6162:47)
```

**Comment by devsullo** [comment]
I have just fixed that disconnect and reconnect bug.. Please check it by reinstalling service.
And please write comment here when you dane it. Thanks

**Comment by johneast** [comment]
I've just tested it and it works. Thanks.

**Comment by devsullo** [comment]
Checkout new update.. instead disconnect use new methods `after` and `done` methods.. Hope it helps you to build scalable apps
